# Generated by Django 4.0.1 on 2022-01-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0002_alter_licenses_options_remove_licenses_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Licenses',
            old_name='linking_from_different_license',
            new_name='different_license',
        ),
    ]
