# Generated by Django 4.0.1 on 2022-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0003_rename_linking_from_different_license_licenses_different_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenses',
            old_name='GPL_approved',
            new_name='GPL_compatible',
        ),
        migrations.AlterField(
            model_name='licenses',
            name='DFSG_compatible',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='FSF_approved',
            field=models.BooleanField(),
        ),
    ]
