# Generated by Django 4.0.1 on 2022-01-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0005_alter_licenses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Licenses',
            options={'ordering': ['license_name']},
        ),
    ]
