# Generated by Django 4.0.1 on 2022-01-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0007_alter_licenses_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
