# Generated by Django 4.0.1 on 2022-01-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0009_gpl_gpl_compatible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPL',
        ),
    ]
