# Generated by Django 4.0.1 on 2022-01-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0010_delete_gpl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Licenses',
            options={'ordering': ['license_name']},
        ),
    ]
