# Generated by Django 4.0.1 on 2022-01-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0011_alter_licenses_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenses',
            name='copyright_holder',
        ),
    ]
