# Generated by Django 4.0.1 on 2022-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0012_remove_licenses_copyright_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='Licenses',
            name='copyright_holder',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
