# Generated by Django 4.0.1 on 2022-01-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0013_licenses_copyright_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Licenses',
            name='guarantees',
        ),
    ]
