# Generated by Django 4.0.1 on 2022-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0014_remove_licenses_guarantees'),
    ]

    operations = [
        migrations.AddField(
            model_name='Licenses',
            name='guarantee',
            field=models.BooleanField(default=True, help_text='Is the license guaranteed?'),
            preserve_default=False,
        ),
    ]
