# Generated by Django 4.0.1 on 2022-02-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0016_remove_licenses_copyright_holder_licenses_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='DFSG_compatible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='FSF_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='GPL_compatible',
            field=models.BooleanField(blank=True, help_text='Is it compatible with GPL?', null=True),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='OSI_approved',
            field=models.BooleanField(blank=True, help_text='Is the OSI license approved?', null=True),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='copyleft',
            field=models.BooleanField(blank=True, default=True, help_text='Is Copyleft a license?', null=True),
        ),
    ]
