# Generated by Django 4.0.1 on 2022-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0017_alter_licenses_dfsg_compatible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='different_license',
            field=models.BooleanField(blank=True, help_text='Allows linking with code under a different license.', null=True),
        ),
    ]
